---
# Default to enable all rules
default: true

# MD007: unordered-list-indent
MD007:
  indent: 4

# MD013: line-length
MD013: true

# MD024: no-duplicate-heading
MD024:
  siblings_only: true

# MD033: no-inline-html
MD033: false

# MD041: first-line-h1
MD041: false
...
