---
name: Deploy docs 📚 to GitHub pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    name: Build and deploy docs 📚
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 🧩
        uses: actions/checkout@v4
      - name: Set up Python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"
      - name: Install MKDocs and plugins 📚
        run: >-
          pip install
          mkdocs-material
          mkdocs-autorefs
          mkdocs-material-extensions
          mkdocstrings
          mkdocstrings-python-legacy
          mkdocs-include-markdown-plugin
      - name: Deploy docs to GitHub pages 📚
        run: |
          mkdocs gh-deploy --force
...
